[package]
name = "costa"
version = "0.1.0"
edition = "2024"

[dependencies]
osta-lexer.workspace = true
osta-parser.workspace = true
osta-session.workspace = true
osta-ast.workspace = true

clap = { version = "4.5.60", features = ["derive"] }

[workspace]
members = ["osta-ast", "osta-index", "osta-lexer", "osta-parser", "osta-session", "osta-syntax"]
resolver = "3"

[workspace.dependencies]
osta-ast = { path = "./osta-ast" }
osta-index = { path = "./osta-index" }
osta-lexer = { path = "./osta-lexer" }
osta-parser = { path = "./osta-parser" }
osta-session = { path = "./osta-session" }
osta-syntax = { path = "./osta-syntax" }

thiserror = "2.0.16"
bumpalo = { version = "3.19.0", features = ["allocator_api"] }
