[package]
name = "costa"
version = "0.1.0"
edition = "2024"

[dependencies]
osta-lexer.workspace = true
osta-parser.workspace = true
osta-session.workspace = true
osta-ast.workspace = true

clap = { version = "4.5.60", features = ["derive"] }

[workspace]
members = ["crates/osta-ast", "crates/osta-index", "crates/osta-lexer", "crates/osta-parser", "crates/osta-session", "crates/osta-syntax"]
resolver = "3"

[workspace.dependencies]
osta-ast = { path = "crates/osta-ast" }
osta-index = { path = "crates/osta-index" }
osta-lexer = { path = "crates/osta-lexer" }
osta-parser = { path = "crates/osta-parser" }
osta-session = { path = "crates/osta-session" }
osta-syntax = { path = "crates/osta-syntax" }

thiserror = "2.0.16"
bumpalo = { version = "3.19.0", features = ["allocator_api"] }
